name: dart_exporter
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.0.0
  build_resolvers: ^2.0.4
  source_gen:
  glob: ^2.0.0
  dart_exporter_annotation:
    path: ../dart_exporter_annotation/

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
