name: dart_exporter
description: generate exports with build runner
version: 3.0.4
homepage: https://github.com/ankiimation/dart_exporter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_exporter_annotation: ^2.0.3
  build_resolvers: ^2.0.4
  build: ^2.3.1
  glob: ^2.0.1
  analyzer: ^6.5.0
  source_gen: ^1.2.3
  yaml: ^3.1.1
  freezed_annotation: ^3.0.0
