name: example_package
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  dart_exporter:
    path: /Users/lenguyenkhoa/Documents/GitHub/dart_exporter/dart_exporter/
  build_runner: ^2.1.2
dependencies:
  dart_exporter_annotation: ^2.0.0

dart_exporter:
  ingore_if_path_matched:
    - .g.dart
    - .gen.dart
    - khoa.dart
  use_export_annotation: true
