name: example_package
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation:
  dart_exporter_annotation:
    path: ../../dart_exporter_annotation

dev_dependencies:
  build_runner: 
  pedantic: 
  dart_exporter:
    path: ../
